config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, at: 'users', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  resources :comments
 
   resources :work_places do
    resources :comments, only:[:index,:new, :create]
  end
  get 'workplaces/find'
  post 'workplaces/find'

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/work_place.rb
class WorkPlace < ApplicationRecord
  #後で必要に応じてアソシエーションを設定する
  belongs_to :user
  has_many :comments , dependent: :destroy
  
  #入力必須項目(name,region,tel)
  validates :name, :region, :tel, presence:{message:'は必須項目です。入力してください'}
  #TEL ⇒重複不可,入力必須
  validates :tel, uniqueness:{message:'はすでに使用されています'}
  #TEL ⇒数値入力に限定
  validates :tel, numericality:{message:'は数値で入力してください'}
  #URL ⇒ URL認証
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/,allow_blank: true

    #img uploader
  # mount_uploader :image, ImageUploader
  # 曖昧検索用メソッド
  def self.search(search)
    return WorkPlace.order(created_at: "DESC").limit(24) unless search
    WorkPlace.where('LOWER(name) LIKE ?', "%#{[search].downcase}%")
  end
end

app/controllers/work_places_controller.rb
class WorkPlacesController < ApplicationController
    protect_from_forgery with: :exception
    before_action :set_current_user
    before_action :authenticate_user!
    #pagination
    PER = 5
  # GET /work_places
  # GET /work_places.json
  def index
    #作成された順に降順で表示
    if user_signed_in?
      # flash[:alert] = 'ログインしました'
      @work_places = WorkPlace.page(params[:page]).per(PER)
      # 検索オブジェクト
      @search = WorkPlace.ransack(params[:q])  
      
      # 検索結果
      @work_places = @search.result
      
    else
      redirect_to root_path
    end
  end
  
 
      # def find
      #   # 店舗が存在し、店舗名も取得できたら・・・
      #   if params[:work_place].present? && params[:work_place][:name]
      #     # 検索オブジェクト
      #   @search = WorkPlace.ransack(params[:work_place])  
      #   #検索内容を小文字にしてあいまい検索 select from `workplaces`.* from `workplaces` where (name LIKE 'OFFICE')
      #   @work_places = @search.where('LOWER(name) LIKE ?', "%#{params[:work_place][:name].downcase}%")
      #   elsif 
      #   @work_places = WorkPlace.all
      #   end
      # end


  # GET /work_places/1
  # GET /work_places/1.json
  # =>loginしていれば全てのユーザーが確認可能
  def show
    if user_signed_in?
      
      @work_place = WorkPlace.find(params[:id])
      @open_hour = @work_place.opentime.hour
      @open_min = @work_place.opentime.strftime("%M")
      @close_hour = @work_place.closetime.hour
      @close_min = @work_place.closetime.strftime("%M")
      
      @comment = Comment.new
      @comment.work_place_id = params[:comment_id]
      
    else
      redirect_to root_path
    end
  end

  # =>registerとadminが使用可能
  def new
    @work_place = WorkPlace.new
  end

  # =>registerは自分のcreateしたもののみ、adminが使用可能
  def edit
    @work_place = WorkPlace.find(params[:id])
  end

  # =>registerとadminが使用可能
  def create
    @work_place = WorkPlace.new(work_place_params)

    respond_to do |format|
      if @work_place.save
        format.html { redirect_to @work_place, notice: 'ご登録ありがとうございます！' }
        format.json { render :show, status: :created, location: @work_place }
      else
        format.html { render :new, notice: '登録に失敗しました'}
        format.json { render json: @work_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_places/1
  # PATCH/PUT /work_places/1.json
  # =>registerは自分のcreateしたもののみ、adminが使用可能
  def update
    @work_place = WorkPlace.find(params[:id])
    respond_to do |format|
      if @work_place.update(work_place_params)
        format.html { redirect_to @work_place, notice: '更新されました' }
        format.json { render :show, status: :ok, location: @work_place }
      else
        format.html { render :edit }
        format.json { render json: @work_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_places/1
  # DELETE /work_places/1.json
  # =>registerは自分のcreateしたもののみ、adminが使用可能
  def destroy
    @work_place = WorkPlace.find(params[:id])
    @work_place.destroy
    respond_to do |format|
      format.html { redirect_to work_places_path, notice: '削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_current_user
      @user = current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_place_params
      params.require(:work_place).permit(:name, :region, :tel, :url, :address, :opentime, :closetime,:image,:user_id)
    end
    
    def search_params
      params.require(:q).permit
    end
end

app/helpers/work_places_helper.rb
module WorkPlacesHelper
end

app/views/work_places/_form.html.erb
<%= form_with(model: @work_place,local: true) do |form| %>
    <%# error出力 %>
    <% if work_place.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(work_place.errors.count, "error") %> error! 保存されませんでした！</h2>
        <ul>
        <% work_place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div  align ="center" class="form_div">
        <table width="60%">
          <tr class="field">
            <td width="20%"><%= form.label :name %></td>
            <td width="40%"><%= form.text_field :name ,:placeholder => "店舗名"%></td>
          </tr>
          
          <tr class="field">
            <td><%= form.label :region %></td>
            <td><%= form.text_field :region ,:placeholder => "地域"%></td>
            <%# 後でプルダウンﾘｽﾄ化したい %>
             <!--select_tag(:region, options_for_select(["東北","関東","中部","信越","関西","中部","四国","九州",]))  ,:placeholder => "地方"-->
          </tr>
          
          <tr class="field">
            <td><%= form.label :TEL %></td>
            <td><%= form.number_field :tel ,:placeholder => "09012345678"%></td>
          </tr>
          <tr class="field">
            <td><%= form.label :Address %></td>
            <td><%= form.text_area :address ,:placeholder => "住所"%></td>
          </tr>
          
          <tr class="field">
            <td><%= form.label :Opentime %></td>
            <td class="timeselect"><%= form.time_select :opentime ,:placeholder => "営業開始", include_blank: true%></td>
          </tr>
          
          <tr class="field">
            <td><%= form.label :Closetime %></td>
            <td class="timeselect"><%= form.time_select :closetime, :placeholder => "営業終了", include_blank: true %></td>
          </tr>
          
          <tr class="field">
            <td><%= form.label :URL %></td>
            <td><%= form.text_area :url , :placeholder => "お店のURLを入力してください", include_blank: true %></td>
          </tr>
          
        </table>
        
        <div class="field">
          <%= form.hidden_field :user_id, :value => @user %>
        </div>
    
        <% if user_signed_in? %>
          <div >
            <%= form.submit value:"登録", data: {disable_with: "Now Loading..."},class: "btn btn-primary form_actions"%>
          </div>
        <% end %>
         
    </div>
<% end %>

app/views/work_places/_form2.html.erb
<%= form_with(model: @comment, url: work_place_comments_path(@work_place.id),method: :post) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.hidden_field :work_place_id, {value:  @work_place.id} %>
    </div>

    <div class="field form2_content">
      <h4 class ="content_label">レビューを追加</h4>
      <%= form.text_area :content ,
      :placeholder => "気にいったこと/気に入らなかったことは何ですか？
最も伝えたいことは何ですか？" ,class: "content_area"%>
    </div>
  
    <div class="field">
      <%= form.hidden_field :user_id, {value: current_user.id} %>
    </div>
    <% if user_signed_in? %>
      <div class="actions">
        <%= form.submit value:"クチコむ", data: {disable_with: "Now Loading..."},
        class: "btn btn-primary form_actions"%>
      </div>
    <% end %>
  <% end %>

app/views/work_places/_search_form.html.erb
<div class="retrive">
  <%= search_form_for @search, url: work_places_path do |f|%>
      <table>
          <thead>
            <tr>
              <!--:name_cont　曖昧検索contain-->
               <th><%= f.search_field :name_cont,:placeholder => "店舗名を入力" %></th>
              <th><%= f.submit "店舗検索" , data: {disable_with: "Now Loading..."}, class:"btn"%></th>
            </tr>
          </thead>
          <tr>
            <th><%= sort_link(@search, :name) -%></th>
            <th><%= sort_link(@search, :id) -%></th>
          </tr>
        </table>
  <% end %>

</div>

app/views/work_places/edit.html.erb
<h1>編集画面</h1>

<%= render 'form', work_place: @work_place %>
<% if user_signed_in? %>
<%= link_to '店舗画面Top', @work_place %> | <%= link_to '戻る', work_places_path %>
<% end %>

<% if user_signed_in?%>
<%= link_to 'プロフィール変更', edit_user_registration_path%>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete%>
<% else%>
<%= link_to '新規登録', new_user_registration_path%>
<%= link_to 'ログイン', new_user_session_path%>
<% end %>

app/views/work_places/find.html.erb
<h1>検索結果 | CoworkingSpace's</h1>
<div class="user_nav">
  <% if user_signed_in?%>
    
      <div><%= render 'search_form'%></div>
      <button class ="btn btn-primary"><%= link_to 'プロフィール変更', edit_user_registration_path%></button>
      <button class ="btn btn-primary"><%= link_to 'ログアウト', destroy_user_session_path,method: :delete %></button>
  
      <% if current_user.role == 'admin' or current_user.role == 'register'%>
        <button class ="btn btn-warning"><%= link_to '店舗登録', new_work_place_path %></button>
      <% end %>
  <% else%>
  <button class ="btn btn-primary"><%= link_to '新規登録', new_user_registration_path%></button>
  <button class ="btn btn-primary"><%= link_to 'ログイン', new_user_session_path%></button>
  <% end %>
</div>

<div class="index_container">
  <% @work_places.each do |w| %>
    <div class="index_stores">
      <p class="index_id">No.<%= w.id %>|</p>
      <p class="index_name"><%= w.name %></p>
      <p class="index_region"><%= w.region %></p>
      <p  class="index_links"><%= link_to 'More・・・', w %></p>
      <div id="app">
        <% if current_user.role == 'admin' or current_user.id == w.user_id%>
          <button class ="btn btn-success "><%= link_to '編集', edit_work_place_path(w) %></button>
          <button class ="btn btn-success "><%= link_to '削除', work_place_path(w), method: :delete, data: { confirm: '本当に削除しますか?' } %></button>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/work_places/index.html.erb
<h1>CoworkingSpace's</h1>
<div class="user_nav">
  <% if user_signed_in?%>
    
      <div><%= render 'search_form'%></div>
      <button class ="btn btn-primary"><%= link_to 'プロフィール変更', edit_user_registration_path%></button>
      <button class ="btn btn-primary"><%= link_to 'ログアウト', destroy_user_session_path,method: :delete %></button>
  
      <% if current_user.role == 'admin' or current_user.role == 'register'%>
        <button class ="btn btn-warning"><%= link_to '店舗登録', new_work_place_path %></button>
      <% end %>
  <% else%>
  <button class ="btn btn-primary"><%= link_to '新規登録', new_user_registration_path%></button>
  <button class ="btn btn-primary"><%= link_to 'ログイン', new_user_session_path%></button>
  <% end %>
</div>

<div class="index_container">
  <% @work_places.each do |w| %>
    <div class="index_stores">
      <p class="index_id">No.<%= w.id %>|</p>
      <p class="index_name"><%= w.name %></p>
      <ul class ="index_region_links">
        <li class="index_region"><%= w.region %></li>
        <li class="index_links"><%= link_to 'More・・', w %></li>
      </ul>
      <div>
        <% if current_user.role == 'admin' or current_user.id == w.user_id%>
          <button class ="btn btn-success index_edit_delete"><%= link_to '編集', edit_work_place_path(w) %></button>
          <button class ="btn btn-success index_edit_delete"><%= link_to '削除', work_place_path(w), method: :delete, data: { confirm: '本当に削除しますか?' } %></button>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/work_places/new.html.erb
<h1>新規店舗登録</h1>

<%= render 'form', work_place: @work_place %>

<%= link_to 'Back', work_places_path %>

app/views/work_places/show.html.erb
<h1>店舗詳細 | CoworkingSpace's</h1>

<div class="user_nav">
  <% if user_signed_in?%>
      <button class ="btn btn-primary"><%= link_to 'プロフィール変更', edit_user_registration_path%></button>
      <button class ="btn btn-primary"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></button>
    <% if current_user.role == 'admin' or current_user.role == 'register'%>
        <button class ="btn btn-success"><%= link_to '編集', edit_work_place_path(@work_place)%></button>
        <button class ="btn btn-success"><%= link_to '削除', @work_place, method: :delete, data: { confirm: '本当に削除しますか?' } %></button>
    <% end %>
  <% else%>
      <button class ="btn btn-primary"><%= link_to '新規登録', new_user_registration_path%></button>
      <button class ="btn btn-primary"><%= link_to 'ログイン', new_user_session_path%></button>
  <% end %>
</div>

<section class="show_section">
  <div class="show_inlineblock">
        <div class="show_ids">
          No.<%= @work_place.id %>
        </div>
        
        <div class="show_name_region">
          <h2 class="show_name"><%= @work_place.name %></h2>
          <h3 class="show_region"><%= @work_place.region %></h3>
        </div>
  </div>
    
        <div class="show_image">
            <% if @work_place.image? %>
              <%= @work_place.image %>
              <strong><%= image_tag @work_place.image.url %></strong>
            <% end %>
        </div>
        

      <div class="show_name_detail">
        <h2 class="show_name2"><%= @work_place.name %></h2>
        <ul class="show_ul">
          <% if @open_hour.present? %>
          <li>営業時間: <%= @open_hour %> : <%= @open_min %> ~ <%= @close_hour %> : <%= @close_min %></li>
          <% end %>
          <li>☎:<%= @work_place.tel %></li>
          <% if @work_place.address.present? %>
          <li>🏠:<%= @work_place.address %></li>
          <% end %>
          <li><%= link_to '店舗Webサイト・・', @work_place.url, class:"show_link" %></li>
        </ul>
      </div>
    
            <button class="top"><%= link_to 'TOP', work_places_path %></button>
      
      <% if @work_place.comments.nil? %>
        <p><%= "現在コメントは 0件です" %></p>
      <% end %>
      
      <div class="content_form" >
      <%= render 'form2', comment: @comment %>
      </div>
      
      <% @work_place.comments.reverse_each  do |re| %>
          <section class ="comment_section">
            
            <div class ="comment_created_at"><%= re.created_at.strftime("%Y年/%m月/%d日 %H時 %M分") %></div>
              <div class="comment_inline">
                <div class ="comment_id">UserID:<%= current_user.id %>さん</div>
                <div class ="comment_content">
                 <p><%= re.content %></p>
                </div>
              </div>
          </section>

      <% end %>
</section>