config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users, at: 'users', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  resources :comments
 
   resources :work_places do
    resources :comments, only:[:index,:new, :create]
  end
  get 'workplaces/find'
  post 'workplaces/find'

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %>
    <%= f.text_field :index %>
  </div>

  <div class="field">
    <%= f.label :show %>
    <%= f.text_field :show %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
  <div class="pagescontainer">
    <h1 id = "border-gradient" data-subtitle="-コワーキングスペース情報サイト-">CoworkingSpace<span class="italic">'s</span></h1>
   
        <button type="button" name="button" class ="btn btn-primary"><%= link_to '新規登録', new_user_registration_path%></button>
        <button type="button" name="button" class ="btn btn-primary"><%= link_to 'ログイン', new_user_session_path%></button>
        
  
      <%= link_to image_tag('top.jpg'), new_user_session_path , class: :topimage%>

  </div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @page.index %>
</p>

<p>
  <strong>Show:</strong>
  <%= @page.show %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>